---
version: ~> 1.0
# for validation of this file

# 18.04
dist: bionic

branches:
  only:
    - master

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
  - pip install cookiecutter
  - pip install poetry

script:
- bash ./test.sh

deploy:
  provider: script
  script: bash deploy-test-pypi.sh
  on:
    #tags: true
    all_branches: true
    python: "3.6"
