---
version: ~> 1.0
# for validation of this file

# 18.04
dist: bionic

branches:
  only:
    - master

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
  - pip install cookiecutter
  - pip install poetry

script:
- bash ./test.sh

deploy:
  provider: script
  script: poetry config repositories.pypi https://test.pypi.org/simple/ && cd iancleary-pypackage && bash scripts/deploy.sh
  on:
    tags: true
    python: "3.6"
