dist: xenial

language: python

cache: pip

python:
    - "3.6"
    - "3.7"
    - "3.8-dev"
    - "nightly"

matrix:
    allow_failures:
        - python: "3.8-dev"
        - python: "nightly"

before_install:
    # Install Poetry
    - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py
    - python get-poetry.py -y
    - echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"

install:
    - pip install flit
    - flit install --symlink

script:
    - bash scripts/test.sh

after_script:
    - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: script
  script: bash scripts/deploy.sh
  on:
    tags: true
    python: "3.6"
